import{Challenge,el,place,rand}from'./base.js';
const make=(meta,run)=>{const factory=ctx=>{const c=new Challenge({...ctx,...meta});c.start=()=>run(c);return c};Object.assign(factory,meta);return factory};
const button=(c,text='TAP',cls='target')=>{const b=el('button',cls,text);c.arena.append(b);return b};
const shuffle=a=>a.sort(()=>Math.random()-.5);
export const challenges=[
make({id:'tap-seven',title:'TAP 7 TIMES.',sub:'Exactly seven. Eight is showing off.',weight:1.2},c=>{let n=0;const b=button(c,'0','center-button');c.listen(b,'pointerdown',e=>{e.preventDefault();n++;b.textContent=n;c.audio.play('click');if(n>7)c.finish(false,'Eight taps. We counted.');else if(n===7)c.later(()=>c.finish(true),180)});c.later(()=>c.finish(false,`${n}/7. Mathematics wins.`),10000)}),
make({id:'hold',title:'HOLD.',sub:'Commit to it.',weight:1.1},c=>{const b=button(c,'HOLD','center-button'),m=el('div','meter'),fill=el('i');m.append(fill);c.arena.append(m);let down=false,p=0,release=false;c.listen(b,'pointerdown',e=>{e.preventDefault();down=true;b.setPointerCapture(e.pointerId)});c.listen(b,'pointerup',()=>{if(release)c.finish(true);else if(p<100)c.finish(false,'You let go. It noticed.')});c.every(()=>{if(down&&!release){p+=2.2+.15*c.difficulty;fill.style.width=p+'%';if(p>58&&c.difficulty>2.4){release=true;c.instruction.textContent='LET GO!';c.sub.textContent='Now!';c.audio.play('warning');c.later(()=>c.finish(false,'You held on too long.'),650)}else if(p>=100)c.finish(true)}},40);c.later(()=>c.finish(false,'You never committed.'),10000)}),
make({id:'dont-touch',title:"DON'T TOUCH ANYTHING.",sub:'Yes, this is the whole challenge.',weight:.85},c=>{for(let i=0;i<6;i++){const x=button(c,['FREE','BONUS','TAP ME','?'][i%4]);place(x,rand(12,88),rand(15,85));x.style.animation=`wobble ${rand(.2,.6)}s infinite`}c.listen(c.arena,'pointerdown',()=>c.finish(false,'You touched something. Predictable.'));c.later(()=>c.finish(true),Math.max(2800,4200-c.difficulty*90))}),
make({id:'catch-him',title:'CATCH HIM!',sub:'Tap the creature before he lands.',weight:1},c=>{const guy=button(c,'ᗧ');guy.style.top='-10%';guy.style.left=rand(15,85)+'%';let y=-10,last=performance.now();const loop=t=>{const dt=t-last;last=t;y+=dt*(.035+c.difficulty*.0025);guy.style.top=y+'%';if(y>92)c.finish(false,'He has left the building.');else c.raf=requestAnimationFrame(loop)};c.listen(guy,'pointerdown',e=>{e.stopPropagation();c.finish(true)});c.raf=requestAnimationFrame(loop)}),
make({id:'wrong-button',title:'PICK THE RIGHT ONE.',sub:'Clue: the truth tells the truth.',weight:1},c=>{const labels=['WRONG','NOPE','NOT THIS','BAD IDEA','I AM RIGHT','NO'];labels.sort(()=>Math.random()-.5).forEach((t,i)=>{const b=button(c,t,'choice');place(b,20+(i%3)*30,25+Math.floor(i/3)*38);c.listen(b,'pointerdown',()=>c.finish(t==='I AM RIGHT',t==='I AM RIGHT'?'':'The label was unusually honest.'))});c.later(()=>c.finish(false,'Indecision is also a decision.'),10000)}),
make({id:'red-go',title:'RED MEANS GO.',sub:'Tap 3 RED circles. Green is dangerous.',weight:1.1},c=>{let hits=0,spawned=0;const spawn=()=>{if(spawned++>=7)return;const safe=Math.random()<.55,b=button(c,safe?'GO':'STOP');b.style.background=safe?'var(--red)':'var(--danger)';place(b,rand(12,88),rand(15,85));c.listen(b,'pointerdown',e=>{e.stopPropagation();if(!safe)c.finish(false,'Green meant stop. We literally said.');else{hits++;b.remove();if(hits===3)c.finish(true)}});c.later(()=>b.remove(),Math.max(650,1300-c.difficulty*45));c.later(spawn,Math.max(350,700-c.difficulty*20))};spawn();c.later(()=>c.finish(false,'Not enough red.'),10000)}),
make({id:'stop-100',title:'STOP AT 100.',sub:'Tap anywhere to freeze.',weight:1},c=>{const n=el('div','big-number','0');c.arena.append(n);let value=0,last=performance.now();const loop=t=>{value+=(t-last)*(.07+c.difficulty*.004);last=t;n.textContent=Math.floor(value);if(value>112)c.finish(false,`Stopped at ${Math.floor(value)}.`);else c.raf=requestAnimationFrame(loop)};c.listen(c.arena,'pointerdown',()=>{const v=Math.floor(value),tol=c.difficulty<2?2:c.difficulty<4?1:0;c.finish(Math.abs(v-100)<=tol,`Stopped at ${v}. So close is still not 100.`)});c.raf=requestAnimationFrame(loop)}),
make({id:'dont-move',title:"DON'T MOVE.",sub:'Hold the target perfectly still.',weight:1},c=>{const b=button(c,'HOLD','center-button');let start,holding=false;c.listen(b,'pointerdown',e=>{holding=true;start=[e.clientX,e.clientY];b.setPointerCapture(e.pointerId);c.arena.classList.add('shake');c.later(()=>holding&&c.finish(true),2600)});c.listen(b,'pointermove',e=>{if(holding&&Math.hypot(e.clientX-start[0],e.clientY-start[1])>Math.max(8,16-c.difficulty))c.finish(false,'Your finger wandered.')});c.listen(b,'pointerup',()=>holding&&c.finish(false,'You moved by letting go.'));c.later(()=>c.finish(false,'You must touch it first.'),10000)}),
make({id:'follow-dot',title:'FOLLOW THE DOT.',sub:'Watch, then repeat the sequence.',weight:1},c=>{const spots=[[20,25],[50,20],[80,28],[25,72],[55,65],[82,76]],len=Math.min(5,3+Math.floor(c.difficulty/3)),seq=Array.from({length:len},()=>Math.floor(Math.random()*6)),dots=spots.map((p,i)=>{const b=button(c,String(i+1),'target');place(b,...p);b.style.opacity='.25';return b});let k=0;seq.forEach((idx,i)=>c.later(()=>{dots.forEach(x=>x.classList.remove('lit'));dots[idx].classList.add('lit');dots[idx].style.opacity='1';c.audio.play('count');c.later(()=>{dots[idx].classList.remove('lit');dots[idx].style.opacity='.25'},350)},500+i*550));c.later(()=>{c.sub.textContent='Your turn.';dots.forEach((b,i)=>c.listen(b,'pointerdown',()=>{if(i!==seq[k])c.finish(false,'Wrong dot. The sequence remembers.');else if(++k===len)c.finish(true)}))},500+len*550);c.later(()=>c.finish(false,'The dots got tired of waiting.'),7500+len*550)}),
make({id:'swipe-away',title:'SWIPE UP!',sub:'Flick all 3 objects away from DANGER.',weight:1},c=>{const zone=el('div','danger-zone','DANGER ZONE');c.arena.append(zone);let cleared=0;for(let i=0;i<3;i++){const b=button(c,'!', 'target draggable');place(b,25+i*25,35+i*8);let sy;c.listen(b,'pointerdown',e=>{sy=e.clientY;b.setPointerCapture(e.pointerId)});c.listen(b,'pointerup',e=>{if(sy-e.clientY>45){b.style.transform='translate(-50%,-300%)';b.style.opacity='0';if(++cleared===3)c.finish(true)}else{b.style.top='83%';c.finish(false,'Wrong direction. Into danger it went.')}})}c.later(()=>c.finish(false,'Danger arrived.'),10000)}),
make({id:'lights-out',title:'LIGHTS OUT.',sub:'Remember the lit tiles.',weight:1},c=>{const grid=el('div','grid');c.arena.append(grid);const pads=Array.from({length:9},(_,i)=>{const p=el('button','pad',String(i+1));grid.append(p);return p}),count=Math.min(5,3+Math.floor(c.difficulty/4)),chosen=[...Array(9).keys()].sort(()=>Math.random()-.5).slice(0,count);chosen.forEach(i=>pads[i].classList.add('lit'));c.later(()=>{pads.forEach(p=>p.classList.remove('lit'));c.sub.textContent=`Tap the ${count} that glowed.`;let left=new Set(chosen);pads.forEach((p,i)=>c.listen(p,'pointerdown',()=>{if(!left.has(i))c.finish(false,'That square was dark.');else{left.delete(i);p.style.opacity='.25';if(!left.size)c.finish(true)}}))},1100);c.later(()=>c.finish(false,'Memory expired.'),10000)}),
make({id:'dont-blink',title:"DON'T BLINK.",sub:'Hold to keep the pupil on its mark.',weight:.9},c=>{const eye=el('div','eye'),pupil=el('i'),mark=el('div','target','✦');mark.style.cssText+='width:42px;height:42px;left:78%;top:42%';eye.append(pupil);c.arena.append(eye,mark);let down=false,x=50;c.listen(c.arena,'pointerdown',()=>down=true);c.listen(c.arena,'pointerup',()=>down=false);c.every(()=>{if(down)x+=1.3;else x-=.45;pupil.style.transform=`translateX(${x-50}px)`;if(x>=76)c.finish(true);if(x<25)c.finish(false,'The pupil drifted. Blink detected-ish.')},35);c.later(()=>c.finish(false,'The eye got bored.'),10000)}),
make({id:'save-button',title:'SAVE THE BUTTON!',sub:'Catch it 4 times.',weight:1.1},c=>{let hit=0;const b=button(c,'DO NOT\nPRESS','target');b.style.whiteSpace='pre-line';const move=()=>place(b,rand(12,88),rand(15,85));move();c.listen(b,'pointerdown',e=>{e.stopPropagation();if(++hit===4)c.finish(true);else{b.textContent=`${4-hit} LEFT`;move()}});c.later(()=>c.finish(false,'The button escaped you.'),10000)}),
make({id:'changed',title:'WHICH ONE CHANGED?',sub:'Look closely.',weight:1},c=>{const icons=['●','▲','■','◆','★','⬟'],grid=el('div','grid');c.arena.append(grid);const pads=icons.map(x=>{const p=el('button','pad',x);grid.append(p);return p}),changed=Math.floor(Math.random()*6),old=icons[changed];c.later(()=>{grid.style.opacity='0';c.later(()=>{pads[changed].textContent=old==='●'?'○':'●';grid.style.opacity='1';c.sub.textContent='Which one?';pads.forEach((p,i)=>c.listen(p,'pointerdown',()=>c.finish(i===changed,i===changed?'':'That one remained loyal.')))},500)},1100);c.later(()=>c.finish(false,'The change went unnoticed.'),8600)}),
make({id:'panic',title:'DO NOTHING.',sub:'Whatever happens.',weight:.85},c=>{c.listen(c.arena,'pointerdown',()=>c.finish(false,'Doing nothing excludes that.'));['CRITICAL!','FIX IT','3','2','1','TOO LATE?'].forEach((t,i)=>c.later(()=>{const a=el('div','fake-alert',t);place(a,rand(15,85),rand(15,85));c.arena.append(a);c.audio.play(i<2?'warning':'count')},i*500));c.later(()=>c.finish(true),3400)}),
// Five original mechanics
make({id:'reaction',title:'WAIT FOR NOW.',sub:"Don't anticipate.",weight:1},c=>{const b=button(c,'WAIT','center-button');let ready=false;c.listen(b,'pointerdown',()=>c.finish(ready,ready?'':'Too early. NOW had not happened.'));c.later(()=>{ready=true;b.textContent='NOW!';b.style.background='var(--cyan)';c.audio.play('warning');c.later(()=>c.finish(false,'Now became never.'),Math.max(500,1050-c.difficulty*25))},rand(1200,2600))}),
make({id:'odd-one',title:'FIND THE ODD ONE.',sub:'One symbol disagrees.',weight:1},c=>{const grid=el('div','grid');c.arena.append(grid);const odd=Math.floor(Math.random()*9),base=Math.random()<.5?'↑':'○';for(let i=0;i<9;i++){const p=el('button','pad',i===odd?(base==='↑'?'↗':'◯'):base);grid.append(p);c.listen(p,'pointerdown',()=>c.finish(i===odd,i===odd?'':'That one was painfully normal.'))}c.later(()=>c.finish(false,'The odd one blended in.'),10000)}),
make({id:'drag-key',title:'UNLOCK IT.',sub:'Drag the key into the lock.',weight:1},c=>{const key=button(c,'◆','target draggable'),lock=el('div','target','▣');place(key,18,70);place(lock,80,25);lock.style.background='#283044';c.arena.append(lock);c.listen(key,'pointerdown',e=>key.setPointerCapture(e.pointerId));c.listen(key,'pointermove',e=>{if(!key.hasPointerCapture(e.pointerId))return;const r=c.arena.getBoundingClientRect();place(key,(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100)});c.listen(key,'pointerup',()=>{const a=key.getBoundingClientRect(),b=lock.getBoundingClientRect();c.finish(Math.hypot(a.x-b.x,a.y-b.y)<80,'The key missed the lock.')});c.later(()=>c.finish(false,'The lock remains smug.'),10000)}),
make({id:'order',title:'SMALLEST TO BIGGEST.',sub:'Tap in size order.',weight:1},c=>{const sizes=[38,54,72,92].sort(()=>Math.random()-.5);let expected=38;sizes.forEach((s,i)=>{const b=button(c,'', 'target');b.style.width=b.style.height=s+'px';place(b,15+i*23,rand(30,70));c.listen(b,'pointerdown',()=>{if(s!==expected)c.finish(false,'That was not the next size.');else{b.remove();expected=[54,72,92,999][[38,54,72,92].indexOf(s)];if(expected===999)c.finish(true)}})});c.later(()=>c.finish(false,'Size matters, eventually.'),10000)}),
make({id:'needle',title:'THREAD THE NEEDLE.',sub:'Stop the line inside the gap.',weight:1},c=>{const track=el('div','line-track'),needle=el('i'),gap=el('span');gap.style.cssText='position:absolute;left:46%;width:8%;height:100%;background:var(--cyan)';track.append(gap,needle);c.arena.append(track);let x=0,dir=1;c.every(()=>{x+=dir*(1.7+c.difficulty*.08);if(x>100||x<0)dir*=-1;needle.style.left=x+'%'},16);c.listen(c.arena,'pointerdown',()=>c.finish(x>=46&&x<=54,`Stopped at ${Math.round(x)}%. The gap was 46–54%.`));c.later(()=>c.finish(false,'The needle kept going.'),10000)}),
// Twenty more quick-fire mechanics
make({id:'double-tap',title:'DOUBLE TAP.',sub:'Two taps. Fast.',weight:1},c=>{const b=button(c,'TAP','center-button');let first=0;c.listen(b,'pointerdown',()=>{const now=performance.now();if(!first){first=now;b.textContent='AGAIN!';c.later(()=>c.finish(false,'That was more of a leisurely pair.'),420)}else c.finish(now-first<420,`Your taps were ${Math.round(now-first)}ms apart.`)});c.later(()=>c.finish(false,'One tap is conspicuously not two.'),10000)}),
make({id:'quick-math',title:'SOLVE IT.',sub:'Tap the correct answer.',weight:1},c=>{const a=Math.floor(rand(3,13)),b=Math.floor(rand(2,10)),answer=a+b;c.instruction.textContent=`${a} + ${b} = ?`;shuffle([answer,answer+1,answer-2,answer+3]).forEach((n,i)=>{const x=button(c,String(n),'choice');place(x,25+(i%2)*50,30+Math.floor(i/2)*40);c.listen(x,'pointerdown',()=>c.finish(n===answer,n===answer?'':'Arithmetic has filed a complaint.'))});c.later(()=>c.finish(false,'The numbers moved on.'),10000)}),
make({id:'stroop',title:'TAP THE INK COLOR.',sub:'Ignore what the word says.',weight:1},c=>{const colors=[['RED','#ff3156'],['BLUE','#4895ff'],['YELLOW','#ffd84d'],['GREEN','#28d978']],ink=Math.floor(rand(0,4)),word=(ink+1+Math.floor(rand(0,3)))%4;const label=el('div','big-number',colors[word][0]);label.style.color=colors[ink][1];label.style.fontSize='clamp(3rem,18vw,7rem)';c.arena.append(label);colors.forEach((v,i)=>{const x=button(c,v[0],'choice');place(x,15+i*23,82);c.listen(x,'pointerdown',()=>c.finish(i===ink,i===ink?'':'You read the word, didn\'t you?'))});c.later(()=>c.finish(false,'The ink dried.'),10000)}),
make({id:'moving-target',title:'HIT THE MOVING TARGET.',sub:'One clean tap.',weight:1},c=>{const b=button(c,'●');let t=0;c.every(()=>{t+=.085+c.difficulty*.002;place(b,50+36*Math.sin(t),50+30*Math.cos(t*1.7))},16);c.listen(b,'pointerdown',e=>{e.stopPropagation();c.finish(true)});c.listen(c.arena,'pointerdown',()=>c.finish(false,'You hit the vast area that was not the target.'));c.later(()=>c.finish(false,'It got away.'),10000)}),
make({id:'count-stars',title:'COUNT THE STARS.',sub:'Choose the total.',weight:1},c=>{const total=Math.floor(rand(3,9));for(let i=0;i<total;i++){const s=el('span','spark','★');place(s,rand(12,88),rand(12,65));c.arena.append(s)}shuffle([total,total+1,total-1]).forEach((n,i)=>{const x=button(c,String(n),'choice');place(x,25+i*25,84);c.listen(x,'pointerdown',()=>c.finish(n===total,n===total?'':'The stars demand a recount.'))});c.later(()=>c.finish(false,'Counting time expired.'),10000)}),
make({id:'tap-order',title:'TAP 1, 2, 3, 4.',sub:'In order. Obviously.',weight:1},c=>{let next=1;shuffle([1,2,3,4]).forEach((n,i)=>{const b=button(c,String(n));place(b,22+(i%2)*56,26+Math.floor(i/2)*48);c.listen(b,'pointerdown',()=>{if(n!==next)c.finish(false,'Numbers have an order.');else{b.remove();if(++next===5)c.finish(true)}})});c.later(()=>c.finish(false,'Four numbers defeated you.'),10000)}),
make({id:'avoid-bombs',title:'COLLECT 4 HEARTS.',sub:'Bombs are not hearts.',weight:1},c=>{let hearts=0,spawned=0;const sequence=shuffle([true,true,true,true,true,false,false,false,false]);const spawn=()=>{if(spawned===sequence.length)return;const safe=sequence[spawned++],b=button(c,safe?'♥':'✹');b.style.background=safe?'var(--cyan)':'var(--red)';place(b,rand(12,88),rand(15,82));c.listen(b,'pointerdown',()=>{if(!safe)c.finish(false,'That was extremely bomb-shaped.');else{b.remove();if(++hearts===4)c.finish(true)}});c.later(()=>b.remove(),900);c.later(spawn,380)};spawn();c.later(()=>c.finish(false,'Not enough love.'),10000)}),
make({id:'vanishing',title:'WHERE WAS IT?',sub:'Remember the target position.',weight:1},c=>{const spots=[[20,25],[50,25],[80,25],[20,70],[50,70],[80,70]],chosen=Math.floor(rand(0,6)),mark=button(c,'?');place(mark,...spots[chosen]);c.later(()=>{mark.remove();c.sub.textContent='Tap its old position.';spots.forEach((p,i)=>{const x=button(c,'','ghost-choice');place(x,...p);c.listen(x,'pointerdown',()=>c.finish(i===chosen,i===chosen?'':'Your spatial memory wandered.'))})},900);c.later(()=>c.finish(false,'The position faded away.'),7900)}),
make({id:'opposites',title:'TAP THE OPPOSITE.',sub:'The arrow lies by omission.',weight:1},c=>{const dirs=[['↑','DOWN'],['→','LEFT'],['↓','UP'],['←','RIGHT']],pick=Math.floor(rand(0,4));const arrow=el('div','big-number',dirs[pick][0]);c.arena.append(arrow);['UP','RIGHT','DOWN','LEFT'].forEach((v,i)=>{const b=button(c,v,'choice');place(b,15+i*23,82);c.listen(b,'pointerdown',()=>c.finish(v===dirs[pick][1],v===dirs[pick][1]?'':'Opposite day remains undefeated.'))});c.later(()=>c.finish(false,'Directionless.'),10000)}),
make({id:'pairs',title:'FIND THE PAIR.',sub:'Two symbols match.',weight:1},c=>{const symbols=shuffle(['▲','●','■','◆','★']),same=symbols[0],items=shuffle([same,same,...symbols.slice(1,5)]),picked=[];items.forEach((v,i)=>{const b=button(c,v,'choice');place(b,20+(i%3)*30,26+Math.floor(i/3)*44);c.listen(b,'pointerdown',()=>{if(picked.includes(i))return;picked.push(i);b.style.background='var(--cyan)';if(picked.length===2)c.finish(items[picked[0]]===items[picked[1]],'Those two are not twins.')})});c.later(()=>c.finish(false,'The pair separated.'),10000)}),
make({id:'higher',title:'PICK THE HIGHER NUMBER.',sub:'Quick comparison.',weight:1},c=>{const a=Math.floor(rand(10,90)),b=a+Math.floor(rand(1,10))*(Math.random()<.5?1:-1);[a,b].forEach((n,i)=>{const x=button(c,String(n),'number-choice');place(x,28+i*44,50);c.listen(x,'pointerdown',()=>c.finish(n===Math.max(a,b),n===Math.max(a,b)?'':'That number is lower. Emotionally and mathematically.'))});c.later(()=>c.finish(false,'Both numbers feel ignored.'),10000)}),
make({id:'release-zone',title:'RELEASE IN THE ZONE.',sub:'Hold, then let go on green.',weight:1},c=>{const b=button(c,'HOLD','center-button');let down=false,ready=false;c.listen(b,'pointerdown',e=>{down=true;b.setPointerCapture(e.pointerId)});c.listen(b,'pointerup',()=>c.finish(ready,ready?'':'Green means release, eventually.'));c.later(()=>{if(!down)return c.finish(false,'You forgot the holding part.');ready=true;b.textContent='RELEASE';b.style.background='var(--cyan)';c.later(()=>c.finish(false,'The green zone closed.'),700)},rand(1000,2200))}),
make({id:'tiny-target',title:'TAP THE TINY DOT.',sub:'Yes, that tiny.',weight:1},c=>{const b=button(c,'','tiny-target');place(b,rand(12,88),rand(15,82));c.listen(b,'pointerdown',e=>{e.stopPropagation();c.finish(true)});c.listen(c.arena,'pointerdown',()=>c.finish(false,'Tiny dot: 1. Giant finger: 0.'));c.later(()=>c.finish(false,'It was small, not invisible.'),10000)}),
make({id:'three-second',title:'WAIT 3 SECONDS.',sub:'Tap when you think three seconds passed.',weight:1},c=>{const start=performance.now(),b=button(c,'STOP','center-button');c.listen(b,'pointerdown',()=>{const elapsed=performance.now()-start;c.finish(Math.abs(elapsed-3000)<450,`That was ${(elapsed/1000).toFixed(1)} seconds.`)});c.later(()=>c.finish(false,'Three seconds became forever.'),10000)}),
make({id:'last-letter',title:'TAP THE LAST LETTER.',sub:'Read all of it.',weight:1},c=>{const word=shuffle(['PANIC','BUTTON','DANGER','ARCADE'])[0];c.instruction.textContent=word;shuffle([...new Set(word)]).forEach((v,i,a)=>{const b=button(c,v,'choice');place(b,50+(i-(a.length-1)/2)*18,55);c.listen(b,'pointerdown',()=>c.finish(v===word.at(-1),v===word.at(-1)?'':'That letter was not last.'))});c.later(()=>c.finish(false,'The last letter left.'),10000)}),
make({id:'center-only',title:'TAP THE CENTER.',sub:'Of the arena, not the button.',weight:1},c=>{const zone=el('button','center-zone','');c.arena.append(zone);c.listen(zone,'pointerdown',e=>{e.stopPropagation();c.finish(true)});c.listen(c.arena,'pointerdown',()=>c.finish(false,'That is not the center.'));c.later(()=>c.finish(false,'The center cannot come to you.'),10000)}),
make({id:'one-safe',title:'ONE IS SAFE.',sub:'The others are traps.',weight:1},c=>{const safe=Math.floor(rand(0,6));for(let i=0;i<6;i++){const b=button(c,i===safe?'✓':'×','choice');place(b,20+(i%3)*30,25+Math.floor(i/3)*45);c.listen(b,'pointerdown',()=>c.finish(i===safe,i===safe?'':'The cross was trying to warn you.'))}c.later(()=>c.finish(false,'Safety timed out.'),10000)}),
make({id:'chase-light',title:'CHASE THE LIGHT.',sub:'Tap the lit pad 4 times.',weight:1},c=>{const grid=el('div','grid');c.arena.append(grid);const pads=Array.from({length:9},()=>{const p=el('button','pad','');grid.append(p);return p});let active=0,hits=0;const move=()=>{pads[active].classList.remove('lit');active=Math.floor(rand(0,9));pads[active].classList.add('lit')};move();pads.forEach((p,i)=>c.listen(p,'pointerdown',()=>{if(i!==active)c.finish(false,'The light was elsewhere.');else if(++hits===4)c.finish(true);else move()}));c.every(move,900);c.later(()=>c.finish(false,'The light outran you.'),10000)}),
make({id:'dont-tap-red',title:'TAP ANYTHING BUT RED.',sub:'A surprisingly specific request.',weight:1},c=>{const colors=['var(--red)','var(--cyan)','var(--yellow)'];colors.forEach((color,i)=>{const b=button(c,'');b.style.background=color;place(b,25+i*25,50);c.listen(b,'pointerdown',()=>c.finish(i!==0,i!==0?'':'You tapped the one forbidden color.'))});c.later(()=>c.finish(false,'Anything would have been something.'),10000)}),
make({id:'rapid-fire',title:'TAP 10. FAST.',sub:'Speed over elegance.',weight:1},c=>{const b=button(c,'10','center-button');let left=10;c.listen(b,'pointerdown',()=>{b.textContent=String(--left);if(!left)c.finish(true)});c.later(()=>c.finish(false,`${left} taps remained.`),10000)})
];
