import{Challenge,el,place,rand}from'./base.js';
const LIMIT=10000,MIN=7000,sh=a=>[...a].sort(()=>Math.random()-.5),cl=(n,a,b)=>Math.max(a,Math.min(b,n));
const make=(m,run)=>{const f=ctx=>{const c=new Challenge({...m,...ctx});c.start=()=>run(c,m);return c};Object.assign(f,m);return f};
const btn=(c,t='',k='target')=>{const b=el('button',k,t);b.type='button';c.arena.append(b);return b},time=(c,msg='Time ran out.',ms=LIMIT)=>c.later(()=>c.finish(false,msg),Math.max(MIN,ms));
const pick=(c,items,answer)=>{const w=el('div','choice-grid');c.arena.append(w);items.forEach((x,i)=>{const b=el('button','arcade-choice',String(x));b.type='button';w.append(b);c.listen(b,'pointerdown',()=>c.finish(i===answer,i===answer?'':'Wrong choice.'))})};
const center=(c,b)=>{place(b,50,52);return b};
const colors={red:'#ff453a',blue:'#0a84ff',green:'#30d158',yellow:'#ffd60a',purple:'#bf5af2'};
function taps(c,m){let n=0,b=center(c,btn(c,'0','hero-button'));c.listen(b,'pointerdown',e=>{e.preventDefault();b.textContent=++n;if(n>m.n)c.finish(false,`You tapped ${n} times.`);else if(n===m.n)c.finish(true)});time(c,`${n}/${m.n} taps.`)}
function hold(c,m){let down=false,start=0,b=center(c,btn(c,'HOLD','hero-button'));c.listen(b,'pointerdown',e=>{down=true;start=performance.now();b.setPointerCapture?.(e.pointerId)});c.listen(b,'pointerup',()=>{if(!down)return;down=false;let d=performance.now()-start;c.finish(Math.abs(d-m.ms)<900,`Held ${(d/1000).toFixed(1)}s.`)});c.every(()=>{if(down&&performance.now()-start>m.ms+900)c.finish(false,'Held too long.')},50);time(c,'Hold incomplete.',11000)}
function odd(c,m){let i=Math.floor(rand(0,9)),g=el('div','tile-grid');c.arena.append(g);for(let x=0;x<9;x++){let b=el('button','tile',x===i?m.b:m.a);b.type='button';g.append(b);c.listen(b,'pointerdown',()=>c.finish(x===i,x===i?'':'That one matched.'))}time(c)}
function math(c,m){let a=Math.floor(rand(3,20)),b=Math.floor(rand(2,12)),ans,q;if(m.op==='+'){ans=a+b;q=`${a} + ${b} = ?`}else if(m.op==='−'){a+=15;ans=a-b;q=`${a} − ${b} = ?`}else{a=Math.floor(rand(2,10));b=Math.floor(rand(2,10));ans=a*b;q=`${a} × ${b} = ?`}c.arena.append(el('div','math-question',q));let vals=sh([ans,ans+1,ans-1,ans+3]);pick(c,vals,vals.indexOf(ans));time(c)}
function memory(c,m){let g=el('div','tile-grid'),pads=[];c.arena.append(g);for(let i=0;i<9;i++){let b=el('button','tile','');b.type='button';g.append(b);pads.push(b)}let chosen=sh([...Array(9).keys()]).slice(0,m.n);chosen.forEach(i=>pads[i].classList.add('lit'));c.later(()=>{pads.forEach(p=>p.classList.remove('lit'));let left=new Set(chosen);pads.forEach((p,i)=>c.listen(p,'pointerdown',()=>{if(!left.has(i))c.finish(false,'Wrong tile.');else{left.delete(i);p.classList.add('picked');if(!left.size)c.finish(true)}}))},1400);time(c,'Memory expired.',11000)}
function reaction(c,m){let ready=false,b=center(c,btn(c,'WAIT','hero-button'));c.listen(b,'pointerdown',()=>c.finish(ready,ready?'':'Too early.'));c.later(()=>{ready=true;b.textContent=m.word;b.classList.add('ready')},rand(1700,3000));time(c,'Too slow.')}
function swipe(c,m){let dirs=['up','right','down','left'],ar=['↑','→','↓','←'],idx=dirs.indexOf(m.dir),b=center(c,btn(c,ar[idx],'swipe-card')),sx=0,sy=0;c.listen(b,'pointerdown',e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture?.(e.pointerId)});c.listen(b,'pointerup',e=>{let dx=e.clientX-sx,dy=e.clientY-sy;if(Math.hypot(dx,dy)<48)return c.finish(false,'Swipe farther.');let d=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');c.finish(d===m.dir,`You swiped ${d}.`)});time(c)}
function order(c,m){let vals=sh([1,2,3,4,5]),target=m.rev?[5,4,3,2,1]:[1,2,3,4,5],k=0,w=el('div','order-row');c.arena.append(w);vals.forEach(v=>{let b=el('button','order-item',v);b.type='button';w.append(b);c.listen(b,'pointerdown',()=>{if(v!==target[k])c.finish(false,'Wrong order.');else{b.disabled=true;b.classList.add('done');if(++k===5)c.finish(true)}})});time(c)}
function color(c,m){let names=Object.keys(colors),target=m.color,spots=[];for(let r=0;r<3;r++)for(let x=0;x<4;x++)spots.push([17+x*22,24+r*28]);let palette=sh([target,target,target,...Array.from({length:9},()=>names[Math.floor(rand(0,names.length))])]),hits=0;palette.forEach((name,i)=>{let b=btn(c,'','color-orb');b.style.background=colors[name];place(b,...spots[i]);c.listen(b,'pointerdown',()=>{if(name!==target)c.finish(false,'Wrong color.');else{b.remove();if(++hits===3)c.finish(true)}})});time(c)}
function count(c,m){let n=Math.floor(rand(4,10)),f=el('div','count-field');c.arena.append(f);let spots=sh([[10,15],[35,15],[60,15],[85,15],[20,45],[50,45],[80,45],[12,75],[40,75],[68,75],[88,75]]);for(let i=0;i<n;i++){let s=el('span','count-symbol',m.shape);s.style.left=spots[i][0]+'%';s.style.top=spots[i][1]+'%';f.append(s)}let vals=sh([n,n+1,n-1,n+2]);pick(c,vals,vals.indexOf(n));time(c)}
function drag(c,m){let a=btn(c,m.a,'drag-piece'),z=el('div','drop-zone',m.b);place(a,20,70);place(z,80,28);c.arena.append(z);let on=false;c.listen(a,'pointerdown',e=>{on=true;a.setPointerCapture?.(e.pointerId)});c.listen(a,'pointermove',e=>{if(!on)return;let r=c.arena.getBoundingClientRect();place(a,cl((e.clientX-r.left)/r.width*100,6,94),cl((e.clientY-r.top)/r.height*100,8,92))});c.listen(a,'pointerup',()=>{on=false;let A=a.getBoundingClientRect(),B=z.getBoundingClientRect();c.finish(Math.hypot(A.x-B.x,A.y-B.y)<100,'Missed the target.')});time(c)}
function slider(c,m){let w=el('div','slider-game'),out=el('div','slider-readout','50%'),r=el('input','arcade-slider'),ok=el('button','confirm-button','SET');r.type='range';r.min=0;r.max=100;r.value=50;w.append(out,r,ok);c.arena.append(w);c.listen(r,'input',()=>out.textContent=r.value+'%');c.listen(ok,'pointerdown',()=>c.finish(Math.abs(+r.value-m.n)<=4,`Set to ${r.value}%.`));time(c)}
function compare(c,m){let nums=[];while(nums.length<4){let n=Math.floor(rand(5,96));if(!nums.includes(n))nums.push(n)}let ans=m.hi?nums.indexOf(Math.max(...nums)):nums.indexOf(Math.min(...nums));pick(c,nums,ans);time(c)}
function doNothing(c,m){if(m.bait)center(c,btn(c,'PRESS','bait-button'));c.listen(c.arena,'pointerdown',()=>c.finish(false,'You touched the screen.'));c.later(()=>c.finish(true),7000)}
function moving(c,m){let b=btn(c,m.s,'moving-target'),hits=0,move=()=>place(b,rand(14,86),rand(18,82));move();c.listen(b,'pointerdown',e=>{e.stopPropagation();if(++hits===3)c.finish(true);else move()});time(c)}
function direction(c,m){let ar=['↑','→','↓','←'],i=Math.floor(rand(0,4));c.arena.append(el('div','direction-hero',ar[i]));let answer=m.mode==='same'?i:(i+2)%4;pick(c,ar,answer);time(c)}
function pairs(c,m){let pair=m.pair,items=sh([pair,pair,m.x,m.y]),w=el('div','pair-grid'),first=null;c.arena.append(w);items.forEach((v,i)=>{let b=el('button','pair-card',v);b.type='button';w.append(b);c.listen(b,'pointerdown',()=>{if(first===null){first=i;b.classList.add('picked')}else c.finish(i!==first&&items[i]===items[first],i!==first&&items[i]===items[first]?'':'Not a pair.')})});time(c)}
function word(c,m){let items=m.items,answer=m.mode==='long'?items.reduce((a,v,i)=>v.length>items[a].length?i:a,0):items.reduce((a,v,i)=>v.length<items[a].length?i:a,0),mix=sh(items.map((v,i)=>({v,i})));pick(c,mix.map(x=>x.v),mix.findIndex(x=>x.i===answer));time(c)}
function precision(c,m){let t=el('div','precision-track'),z=el('span','precision-zone'),n=el('i','precision-needle');z.style.left=m.a+'%';z.style.width=(m.b-m.a)+'%';t.append(z,n);c.arena.append(t);let x=0,d=1;c.every(()=>{x+=d*1.6;if(x>=100||x<=0)d*=-1;n.style.left=x+'%'},16);c.listen(c.arena,'pointerdown',()=>c.finish(x>=m.a&&x<=m.b,`Stopped at ${Math.round(x)}%.`));time(c)}
const specs=[];const add=(kind,rows)=>rows.forEach(r=>specs.push({kind,id:`${kind}-${specs.length+1}`,weight:1,...r}));
add('taps',[3,5,7,9,11].map(n=>({title:`TAP ${n} TIMES.`,sub:'Exactly.',n})));
add('hold',[1500,2000,2500,3000,3500].map(ms=>({title:`HOLD ${(ms/1000).toFixed(1)} SECONDS.`,sub:'Release near the time.',ms})));
add('odd',[['●','○'],['■','□'],['★','☆'],['▲','△'],['◆','◇']].map(([a,b])=>({title:'FIND THE ODD ONE.',sub:'One is different.',a,b})));
add('math',['+','−','×','+','−'].map(op=>({title:'SOLVE IT.',sub:'Choose the answer.',op})));
add('memory',[3,4,5,3,4].map(n=>({title:`REMEMBER ${n} TILES.`,sub:'Then tap them.',n})));
add('reaction',['GO!','NOW!','READY!','GREEN!','TAP!'].map(word=>({title:`WAIT FOR ${word.replace('!','')}.`,sub:'Do not tap early.',word})));
add('swipe',['up','right','down','left','up'].map(dir=>({title:`SWIPE ${dir.toUpperCase()}.`,sub:'One clean swipe.',dir})));
add('order',[false,true,false,true,false].map(rev=>({title:rev?'5 → 1.':'1 → 5.',sub:'Tap in order.',rev})));
add('color',['red','blue','green','yellow','purple'].map(color=>({title:`TAP ${color.toUpperCase()}.`,sub:'Tap three.',color})));
add('count',['●','★','■','▲','♥'].map(shape=>({title:'COUNT THEM.',sub:'Choose the total.',shape})));
add('drag',[['◆','▣'],['★','○'],['■','⌂'],['●','◎'],['♦','▤']].map(([a,b])=>({title:'DRAG TO TARGET.',sub:'Drop it inside.',a,b})));
add('slider',[20,35,50,70,85].map(n=>({title:`SET ${n}%.`,sub:'Within four points.',n})));
add('compare',[true,false,true,false,true].map(hi=>({title:hi?'TAP THE LARGEST.':'TAP THE SMALLEST.',sub:'Compare the numbers.',hi})));
add('doNothing',[false,true,false,true,false].map(bait=>({title:'DO NOTHING.',sub:'No input.',bait})));
add('moving',['●','★','♥','⚡','◆'].map(s=>({title:'CATCH IT 3 TIMES.',sub:'Tap the moving target.',s})));
add('direction',['same','opposite','same','opposite','same'].map(mode=>({title:mode==='same'?'MATCH THE ARROW.':'TAP THE OPPOSITE.',sub:'Choose direction.',mode})));
add('pairs',[['A','B','C'],['7','2','9'],['●','■','▲'],['★','♥','◆'],['X','Y','Z']].map(([pair,x,y])=>({title:'MATCH THE PAIR.',sub:'Find two identical.',pair,x,y})));
add('word',[{mode:'long',items:['CAT','ELEPHANT','BIRD','FOX']},{mode:'short',items:['BLUE','RED','PURPLE','GREEN']},{mode:'long',items:['SUN','MOUNTAIN','SEA','SKY']},{mode:'short',items:['APPLE','FIG','BANANA','MANGO']},{mode:'long',items:['GO','READY','WAIT','START']}].map(x=>({title:x.mode==='long'?'LONGEST WORD.':'SHORTEST WORD.',sub:'Read first.',...x})));
add('precision',[[45,55],[20,30],[70,80],[48,52],[35,50]].map(([a,b])=>({title:'STOP IN THE ZONE.',sub:'Tap at the right moment.',a,b})));
add('math',[{op:'+'},{op:'−'},{op:'×'},{op:'+'},{op:'×'}].map(x=>({title:'QUICK MATH.',sub:'Choose the answer.',...x})));
const run={taps,hold,odd,math,memory,reaction,swipe,order,color,count,drag,slider,compare,doNothing,moving,direction,pairs,word,precision};
export const challenges=specs.slice(0,100).map(m=>make(m,(c,x)=>run[x.kind](c,x)));
export const challengeCount=challenges.length;
